import {
  useState,
  useEffect
} from 'react'

interface optionsInterface {
  value: string,
  option: string
}

export default function useOptions() {
  const [ options, setOptions ] = useState<Array<optionsInterface>>([])
  const values = ["000webhost>000webhost",
  "1and1>1and1",
  "1-password>1Password",
  "2600hz>2600hertz",
  "2k>2k",
  "4chan>4chan",
  "7daystodie>7 Days to Die",
  "8x8>8x8",
  "abc-us>ABC",
  "abebook>Abebooks",
  "absolver>Absolver",
  "accesoneinc>Access One",
  "acorns>Acorns",
  "adams-networks>Adams Networks",
  "adobe-connect>Adobe Connect",
  "adobe-creative-cloud>Adobe Creative Cloud",
  "adp>ADP",
  "adt>ADT",
  "adyen>Adyen",
  "aer-lingus>Aer Lingus",
  "agar-io>Agar.io",
  "air-canada>Air Canada",
  "airbnb>Airbnb",
  "airespring>AireSpring",
  "airnow>Airnow.gov",
  "airtable>Airtable",
  "akamai>Akamai",
  "alaska-airlines>Alaska Airlines",
  "alaskacommunications>Alaska Communications",
  "albion-online>Albion Online",
  "amazon-alexa>Alexa",
  "aliexpress>AliExpress",
  "all-west-communications>All West Communications",
  "allegiant-air>Allegiant Air",
  "ally>Ally",
  "amazon>Amazon",
  "amazon-prime-music>Amazon Prime Music",
  "amazon-prime-instant-video>Amazon Prime Video",
  "aws-amazon-web-services>Amazon Web Services",
  "american-airlines>American Airlines",
  "americanexpress>American Express",
  "amex-serve>American Express Serve",
  "american-messaging>American Messaging",
  "amino>Amino Apps",
  "ammyy>Ammyy",
  "among-us>Among Us",
  "amtrak>Amtrak",
  "ancestorsgame>Ancestors: The Humankind Odyssey",
  "ancestry>Ancestry",
  "anno-1800>Anno 1800",
  "anthem>Anthem",
  "antietam>Antietam",
  "anydesk>Anydesk",
  "aol>AOL",
  "apex-legends>Apex Legends",
  "app-store>App Store",
  "apple-fitness>Apple Fitness+",
  "apple-homekit>Apple HomeKit",
  "apple-maps>Apple Maps",
  "apple-music>Apple Music",
  "apple-news>Apple News",
  "apple-store>Apple Store",
  "apple-support>Apple Support",
  "apple-tv>Apple TV",
  "apple-tv-plus>Apple TV+",
  "appriver>Appriver",
  "appvalley>AppValley",
  "arbuckle>Arbuckle",
  "archeage>ArcheAge",
  "archive-of-our-own>Archive of Our Own",
  "ark>ARK: Survival Evolved",
  "arlo>Arlo",
  "armstrong>Armstrong",
  "arvest>Arvest Bank",
  "arvig>Arvig",
  "asana>Asana",
  "assassins-creed>Assassin&#x27;s Creed",
  "asus>Asus US",
  "att>AT&amp;T",
  "atttv>AT&amp;T TV",
  "atlantic-broadband>Atlantic Broadband",
  "auth0>Auth0",
  "authorize-net>Authorize.net",
  "autotask>Autotask",
  "backblaze>Backblaze",
  "badoo>Badoo",
  "banco-popular-dominicano>Banco Popular Dominicano",
  "bandcamp>Bandcamp",
  "bandwidth>Bandwidth",
  "bank-of-america>Bank of America",
  "bankjerusalem>Bank of Jerusalem",
  "bankofthewest>Bank of the West",
  "barclays>Barclays",
  "bart>BART",
  "basecamp>Basecamp",
  "telltale-games>Batman The Telltale Series",
  "batallion-1944>Battalion 1944",
  "battleborn>Battleborn",
  "battlefield>Battlefield",
  "battlerite>Battlerite",
  "bbt>BB&amp;T",
  "bbva>BBVA",
  "beats-music>Beats Music",
  "bein>beIN",
  "bejeweled>Bejeweled",
  "benbroadband>Bendbroadband",
  "best-buy>Best Buy",
  "bet>BET",
  "bet365>Bet365",
  "bethesda>Bethesda",
  "bill-com>Bill.com",
  "binance>Binance",
  "bing>Bing",
  "bitbucket>Bitbucket",
  "bitchute>BitChute",
  "bitfinex>Bitfinex",
  "bitflyer>Bitflyer",
  "bitstamp>Bitstamp",
  "bittrex>Bittrex",
  "blackdesertdown>Black Desert Online",
  "blackberry>BlackBerry",
  "blackboard>Blackboard",
  "blade-and-soul>Blade and Soul",
  "blazing-hog>Blazing Hog",
  "battle-net>Blizzard Battle.net",
  "blogger>Blogger",
  "blue-jay-wireless>Blue Jay Wireless",
  "bluebird>Bluebird",
  "bluehost>Bluehost",
  "bluejeans>BlueJeans",
  "bmo-harris>BMO Harris Bank",
  "bmw-connected-drive>BMW ConnectedDrive",
  "bnymellon>BNY Mellon",
  "boingo>Boingo",
  "booking-com>Booking.com",
  "boom-beach>Boom Beach",
  "borealis-broadband>Borealis Broadband",
  "box>Box",
  "boycom>BOYCOM Cablevision",
  "braintree>Braintree",
  "brawl-stars>Brawl Stars",
  "brawlhalla>Brawlhalla",
  "bridge_base_online>Bridge Base Online",
  "bring-a-trailer>Bring A Trailer",
  "bt-british-telecom>BT",
  "buckeye-cablesystem>Buckeye Cablesystem",
  "buffer>Buffer",
  "bullet-force>Bullet Force",
  "bumble>Bumble",
  "bwin>Bwin",
  "c-spire>C Spire",
  "cableamerica>CableAmerica",
  "california-iso>California Independent System Operator (CAISO)",
  "call-of-duty>Call of Duty",
  "calltower>CallTower",
  "caltrain>Caltrain",
  "candy-crush>Candy Crush",
  "candy-crush-soda>Candy Crush Soda Saga",
  "canva>Canva",
  "instructure>Canvas by Instructure",
  "capital-one>Capital One",
  "careershift>CareerShift",
  "cash-app>Cash App",
  "cbs_all_access>CBS All Access",
  "cbssports>CBSSports",
  "centerpoint_energy>CenterPoint Energy",
  "cdc>Centers for Disease Control",
  "central-bank>Central Bank",
  "central-hudson>Central Hudson",
  "centralmainepower>Central Maine Power",
  "century-national-bank>Century National Bank",
  "centurylink>CenturyLink",
  "champions-legion>Champions Legion",
  "change-org>Change.org",
  "charles-schwab>Charles Schwab",
  "chase>Chase",
  "chegg>Chegg",
  "chewy>Chewy",
  "chicago-transit-authority>Chicago Transit Authority",
  "chime>Chime",
  "chrome-web-store>Chrome Web Store",
  "chuffed>Chuffed",
  "cigna>Cigna",
  "cincinnati-bell>Cincinnati Bell",
  "cirranet>Cirra Networks",
  "cisco_webex_teams>Cisco Webex Teams",
  "citi>Citi",
  "citizens-bank>Citizens Bank",
  "cityofmontbelvieu>City of Mont Belvieu",
  "civilization>Civilization",
  "clash-of-clans>Clash of Clans",
  "clash-royale>Clash Royale",
  "classlink>Classlink",
  "classy>Classy",
  "clear>Clear",
  "clever>Clever",
  "clickfunnels>ClickFunnels",
  "clickup>ClickUp",
  "cloudflare>Cloudflare",
  "cloudli>Cloudii",
  "cloudsmith>Cloudsmith",
  "cloudtrax>Cloudtrax",
  "cnet>CNET",
  "cnn>CNN",
  "codeacademy>Codeacademy",
  "cogent>Cogent",
  "coinbase>Coinbase",
  "colgia>Colēgia",
  "comedy-central>Comedy Central",
  "common-app>Common App",
  "comporium>Comporium",
  "conan-exiles>Conan Exiles",
  "concur>Concur",
  "confluence>Confluence",
  "connectwise>ConnectWise",
  "consolidated>Consolidated",
  "coned>Consolidated Edison",
  "constant-contact>Constant Contact",
  "consumer-cellular>Consumer Cellular",
  "copy>Copy.com",
  "coredial>Coredial",
  "costco>Costco",
  "counter-strike>Counter-strike",
  "coursera>Coursera",
  "cox-communications>Cox",
  "crackle>Crackle",
  "craigslist>Craigslist",
  "credit-karma>Credit Karma",
  "credit-one-bank>Credit One Bank",
  "creditone-bank>CreditOne Bank",
  "crexendo>Crexendo",
  "cricket-wireless>Cricket Wireless",
  "lightower>Crown Castle",
  "crunchyroll>Crunchyroll",
  "cryptopia>Cryptopia",
  "cvent>Cvent",
  "dailymotion>Dailymotion",
  "dankmemer>Dank Memer",
  "dark-souls>Dark Souls.",
  "dauntless>Dauntless",
  "day-one>Day One",
  "dayz>DayZ",
  "dazn>Dazn",
  "dc-universe-online>DC Universe Online",
  "dead-by-daylight>Dead By Daylight",
  "deathstranding>Death Stranding",
  "deezer>Deezer",
  "defiance-2050>Defiance 2050",
  "delta-air-lines>Delta Air Lines",
  "desire2learn>Desire2Learn",
  "destiny>Destiny",
  "deviantart>DeviantArt",
  "dexcom>Dexcom",
  "difm>Di.fm",
  "diablo>Diablo",
  "digikey>Digikey",
  "digipcservers>DigiPCservers",
  "digitalocean>DigitalOcean",
  "directv>DirecTV",
  "DIRECTVSTREAM>DIRECTV STREAM",
  "zaumstudio>Disco Elysium",
  "discord>Discord",
  "discover>Discover",
  "dish-network>Dish Network",
  "disneyworld>Disney World",
  "disney-plus>Disney+",
  "disqus>Disqus",
  "dissenter>Dissenter",
  "dvlottery>Diversity Lottery",
  "dlive>Dlive",
  "dochub>DocHub",
  "docker>Docker",
  "docusign>DocuSign",
  "dominionenergy>Dominin Energy",
  "don-johnson>Don Johnson",
  "donorschoose>DonorsChoose",
  "doom>Doom",
  "doordash>Doordash",
  "dota-2>Dota 2",
  "doublelist>Doublelist",
  "downforeverybodyorjustme>Downforeveryoneorjustme",
  "draftkings>Draftkings",
  "dragon-ball>Dragon Ball",
  "dragonball-z>Dragon Ball Z: Kakarot",
  "dramafever>Dramafever",
  "dreamhost>DreamHost",
  "driveclub>Driveclub",
  "dropbox>Dropbox",
  "dte-energy>DTE Energy",
  "duckduckgo>Duckduckgo",
  "duelingbook>Duelingbook",
  "duke-energy>Duke Energy",
  "duo>Duo",
  "duolingo>Duolingo",
  "dyl>Dyl",
  "dyn>Dyn",
  "e-trade>E-Trade",
  "ea>EA",
  "ea-sport-ufc>EA Sports UFC",
  "eaglecom>Eagle Communications",
  "earnest>Earnest",
  "earthlink>Earthlink",
  "eatel>Eatel",
  "ebay>eBay",
  "echostar>Echostar",
  "eclinicalworks>eClinicalWorks",
  "ecobee>Ecobee",
  "edx>edX",
  "efax>eFax",
  "epb>Electric Power Board",
  "elevateinternet>Elevate Internet",
  "elite-dangerous>Elite: Dangerous",
  "ello>Ello",
  "emoney>eMoney",
  "endicia>Endicia",
  "engine-yard>Engine Yard",
  "enom>eNom",
  "epbfi>EPB Chattanooga",
  "epic-games-store>Epic Games Store",
  "escape-from-tarkov>Escape from Tarkov",
  "espn>ESPN",
  "espn-plus>ESPN Plus",
  "etherdelta>Etherdelta",
  "etoro>Etoro",
  "etsy>Etsy",
  "eufy>Eufy",
  "eveonline>EVE Online",
  "evevalkyrie>EVE Valkyrie",
  "eventbrite-us>Eventbrite",
  "evernote>Evernote",
  "everquest>Everquest",
  "everydayhero>EveryDayHero",
  "examsoft>ExamSoft",
  "exchange>Exchange Online",
  "exede>Exede",
  "expedia>Expedia",
  "expensify>Expensify",
  "experian>Experian",
  "explorelearning>ExploreLearning",
  "express-scripts>Express Scripts",
  "express-vpn>ExpressVPN",
  "faceapp>Faceapp",
  "facebook>Facebook",
  "facebook-messenger>Facebook Messenger",
  "faceit>Faceit",
  "facetime>Facetime",
  "fafsa>FAFSA",
  "fairpoint-communications>FairPoint",
  "fall-guys>Fall Guys",
  "fallout>Fallout",
  "family-search>Family Search",
  "fandango>Fandango",
  "fandom>Fandom",
  "fanduel>Fanduel",
  "fanfiction>Fanfiction",
  "far-cry>Far Cry",
  "fark>Fark",
  "fastly>Fastly",
  "fastmail>FastMail",
  "fatcow>Fatcow",
  "fax2mail>Fax2mail",
  "fedex>FedEx",
  "feedly>Feedly",
  "fidelity>Fidelity",
  "fifa>Fifa",
  "figma>Figma",
  "finalfantasyviipc>Final Fantasy",
  "find-my-iphone>Find my iPhone",
  "firstcomm>First Communications",
  "first-horizon>First Horizon",
  "firstenergycorp>FirstEnergy",
  "firstlight>FirstLight",
  "firstnet>FirstNet",
  "fitbit>Fitbit",
  "fite>Fite",
  "five9>Five9",
  "fivem>FiveM",
  "fiverr>Fiverr",
  "flickr>Flickr",
  "flightradar24>Flightradar24",
  "fling>Fling",
  "flipboard>Flipboard",
  "flock>Flock",
  "fpl>Florida Power &amp; Light",
  "floridavirtualschool>Florida Virtual School",
  "for-honor>For Honor",
  "forgeofempires>Forge Of Empires",
  "fortnite>Fortnite",
  "forza-motorsport>Forza",
  "fox-news>Fox News",
  "fox-sports-go>Fox Sports Go",
  "frankfort-plantboard>Frankfort PlantBoard",
  "free-fire>Free Fire",
  "freedompop>Freedompop",
  "freepik>Freepik",
  "freshdesk>freshdesk",
  "freshservice>Freshservice",
  "friday-the-13th>Friday the 13th The Game",
  "frii>Frii",
  "frontier>Frontier",
  "frontier-airlines>Frontier Airlines",
  "fubo-tv>FuboTV",
  "fundly>Fundly",
  "fundrazr>FundRazr",
  "funimation>Funimation",
  "fur-affinity>Fur Affinity",
  "fusionconnect>Fusion Connect",
  "futurequest>FutureQuest",
  "fuze>Fuze",
  "fxnow>FXNOW",
  "g-portal>G-Portal",
  "g2a>G2A.com",
  "gab>Gab",
  "game-of-thrones-conquest>Game of Thrones Conquest",
  "game-of-war>Game of war",
  "gamebattles>Gamebattles",
  "gameloft>Gameloft",
  "gamestop>Gamestop",
  "gang-beasts>Gang Beasts",
  "garmin>Garmin",
  "connect-garmin>Garmin Connect",
  "gasbuddy>Gasbuddy",
  "gatehub>Gatehub",
  "gci>GCI",
  "gearsofwar>Gears of War",
  "geeking>Geeking",
  "gemini>Gemini",
  "gems-of-war>Gems of war",
  "genshin-impact>Genshin Impact",
  "geocaching>Geocaching",
  "georgia-power>Georgia Power",
  "gfycat>Gfycat",
  "ghost>Ghost",
  "ghost-recon>Ghost Recon",
  "ghosttunes>Ghosttunes",
  "github>GitHub",
  "gitlab>Gitlab",
  "givecampus>GiveCampus",
  "glassdoor>Glassdoor",
  "glide>Glide",
  "glitch>Glitch",
  "gmail>Gmail",
  "go-daddy>Go Daddy",
  "gofundme>GoFundMe",
  "gog-com>GOG.com",
  "goguardian>GoGuardian",
  "goldman-sachs>Goldman Sachs",
  "google>Google",
  "google-analytics>Google Analytics",
  "google-calendar>Google Calendar",
  "google-classroom>Google Classroom",
  "google-cloud>Google Cloud",
  "google-drive>Google Drive",
  "google-duo>Google Duo",
  "google-fiber>Google Fiber",
  "google-hangouts>Google Hangouts",
  "google-home>Google Home",
  "google-maps>Google Maps",
  "google-meet>Google Meet",
  "google-photos>Google Photos",
  "google-play>Google Play",
  "stadiagoogle>Google Stadia",
  "gotoconnect>GoToConnect",
  "gotomeeting>GoToMeeting",
  "grafana>Grafana Labs",
  "grammarly>Grammarly",
  "gran-turismo>Gran Turismo",
  "grande>Grande",
  "grayson-collin-electric-cooperative-gcec>Grayson Collin Electric Cooperative",
  "greenlight>Greenlight",
  "grindr>Grindr",
  "groove-music>Groove Music",
  "groupme>Groupme",
  "groupon>Groupon",
  "growtopia>Growtopia",
  "grubhub>Grubhub",
  "gta5>GTA 5",
  "gtt>GTT",
  "guild-wars-2>Guild Wars 2",
  "hr-block>H&amp;R Block",
  "halo>Halo",
  "halo-wars>Halo Wars",
  "happn>Happn",
  "hargray>Hargray",
  "harry-potter-wizards-unite>Harry Potter: Wizards Unite",
  "hashflare>Hashflare",
  "hawaiian-airlines>Hawaiian Airlines",
  "hawaiian-telcom>Hawaiian Telcom",
  "hay-day>Hay Day",
  "hayu>Hayu",
  "hbo-go>HBO Go",
  "hbo-max>HBO Max",
  "hbo-now>HBO Now",
  "healthcare-gov>Healthcare.gov",
  "hearthstone>Hearthstone",
  "heartland>Heartland",
  "hello-mobile>Hello Mobile",
  "heroku>Heroku",
  "hibid>HiBid",
  "hidive>HiDive",
  "hilton>Hilton",
  "hinge>HInge",
  "hipchat>Hipchat",
  "hitbtc>HitBTC",
  "hitman>Hitman",
  "hive>Hive",
  "honey>Honey",
  "honeywell>Honeywell",
  "hootsuite>Hootsuite",
  "horizonsatellite>Horizon Satellite",
  "hostgator>Hostgator",
  "hosting24>Hosting24",
  "hostinger-us>Hostinger",
  "hostmonster>Hostmonster",
  "hotels-com>Hotels.com",
  "hotwire>Hotwire",
  "houseparty>HouseParty",
  "hq-trivia>HQ Trivia",
  "hsbc>HSBC",
  "hubspot>Hubspot",
  "hudson-valley-wireless>Hudson Valley Wireless",
  "hue>Hue",
  "hughesnet>HughesNet",
  "hulu>Hulu",
  "humanity>Humanity",
  "humble-bundle>Humble Bundle",
  "hunt-showdown>Hunt: showdown",
  "he>Hurricane Electric",
  "hyatt>Hyatt",
  "hyperwallet>Hyperwallet",
  "i-ready>i-Ready",
  "i3broadband>I3 Broadband",
  "ibm-cloud>IBM Cloud",
  "icici-bank-us>ICICI Bank United States",
  "icloud>iCloud",
  "icq>ICQ",
  "id-me>ID Me",
  "ifttt>IFTTT",
  "ifunny>iFunny",
  "ign>IGN",
  "igtv>IGTV",
  "iheartradio>iHeartRadio‎",
  "ikea>IKEA",
  "illinois-gov>Illinois Century Network",
  "imdb-freedrive>IMDb Freedrive",
  "imessage>iMessage",
  "imgur>Imgur",
  "imvu>IMVU",
  "inbox>Inbox",
  "incontact>inContact",
  "indeed>Indeed",
  "indiegogo>Indiegogo",
  "inet>iNet",
  "infinite_campus>Infinite Campus",
  "infusionsoft>Infusionsoft by Keap",
  "ingress>Ingress",
  "injustice>Injustice 2",
  "inmotion>Inmotion",
  "instacart>Instacart",
  "instagram>Instagram",
  "integra>Integra",
  "inter-mountain-cable>Inter Mountain Cable",
  "interactive-brokers>Interactive Brokers",
  "intermedia>Intermedia",
  "imdb>Internet Movie Database (IMDb)",
  "intralinks>Intralinks",
  "invixium>Invixium",
  "ipage>Ipage",
  "ip-vanish>IPVanish VPN",
  "iqcent>IQcent",
  "iracing>iRacing",
  "iridium>Iridium",
  "ironsight>Ironsight",
  "irs>IRS",
  "itslearning>itslearning",
  "itunes>iTunes",
  "itunes-connect>iTunes Connect",
  "itunes-match>iTunes Match",
  "iwork>iWork",
  "jabber>Jabber",
  "jackbox>Jackbox",
  "jamf-school>Jamf School",
  "jetblue-airways>JetBlue Airways",
  "jira>Jira",
  "jive>Jive",
  "jp-morgan>JP Morgan",
  "juno>Juno",
  "jurassic-world-alive>Jurassic World Alive",
  "kahn-academy>Kahn Academy",
  "kaltrua>Kaltura",
  "kayak>Kayak",
  "keek>Keek",
  "kickstarter>Kickstarter",
  "kik>Kik",
  "kingdomhearts3>Kingdom Hearts 3",
  "klarna>Klarna",
  "knockoutcity>Knockout City",
  "kraken-exchange>Kraken",
  "kucoin>Kucoin",
  "kumo-cloud>Kumo Cloud",
  "last-fm>last.fm",
  "lastpass>LastPass",
  "lawbreakers>LawBreakers",
  "layer3-tv>Layer3 TV",
  "leaco>Leaco",
  "league-of-legends>League of Legends",
  "league-of-legends-wild-rift>League of Legends: Wild Rift",
  "life360>Life360",
  "lifesize>Lifesize",
  "lightpath>Lightpath",
  "limebike>Limebike",
  "limelight>Limelight Networks",
  "line>Line",
  "linkedin>LinkedIn",
  "linode>Linode",
  "liquid-web>Liquid Web",
  "liveleak>LiveLeak",
  "liveperson>Liveperson",
  "locast>Locast",
  "logix>Logix",
  "logmein>Logmein",
  "lolawireless>Lola Wireless",
  "lowes>Lowe&#x27;s",
  "lsnetworks>LS Networks",
  "lumos-networks>Lumos Networks",
  "lyft>Lyft",
  "lynda>Lynda",
  "os-x-software-update>macOS Update",
  "madden>Madden",
  "maguss>Maguss",
  "mail-com>Mail.com",
  "mailbox>Mailbox",
  "mailchimp>Mailchimp",
  "maknet>MakNet",
  "manhunt>Manhunt",
  "mariokarttour>Mario Kart Tour",
  "marriott>Marriott",
  "marta>MARTA",
  "marvel>Marvel",
  "marvel-contest-of-champions>Marvel Contest of Champions",
  "maryland-transit-administration-mta>Maryland Transit Administration (MTA)",
  "mashable>Mashable",
  "masseffect>Mass Effect",
  "mastercard>Mastercard",
  "maxxsouth>MaxxSouth",
  "mbta>MBTA",
  "mcdonalds>McDonalds app",
  "mediatemple>Media Temple",
  "mediacom-communications>Mediacom",
  "medicare>Medicare",
  "meetme>Meetme",
  "meetup>Meetup",
  "mega>Mega",
  "megapath>Megapath",
  "membean>Membean",
  "mercury-wireless>Mercury Wireless",
  "merrill-lynch>Merrill Lynch",
  "metra>Metra",
  "metrc>Metrc",
  "metrobyt-mobile>Metro by T-Mobile",
  "metrolink>Metrolink",
  "metronetinc>Metronetinc",
  "mewe>MeWe",
  "mhz-choice>MHz Choice",
  "miami-dade-transit>Miami Dade Transit",
  "micro-center>Micro Center",
  "microsoft>Microsoft",
  "windows-azure>Microsoft Azure",
  "teams>Microsoft Teams",
  "vlsc>Microsoft VLSC",
  "midcontinent>Midcontinent Media",
  "milanote>Milanote",
  "mimecast>Mimecast",
  "minecraft>Minecraft",
  "mint>Mint",
  "mint-mobile>Mint Mobile",
  "mitel>Mitel",
  "mixer>Mixer",
  "mlb-the-show>MLB The Show",
  "mlb-tv>MLB TV",
  "mobile-legends>Mobile legends",
  "mobile-strike>Mobile Strike",
  "molina-healthcare>Molina Healthcare",
  "momentum-telecom>Momentum Telecom",
  "moneylion>Moneylion",
  "monster-hunter>Monster Hunter",
  "moodle>Moodle",
  "mordhau>Mordhau",
  "morgan_stanley>Morgan Stanley",
  "mortalkombat>Mortal Kombat",
  "mouser>Mouser",
  "moviepass>Moviepass",
  "movies-anywhere>Movies Anywhere",
  "movietickets>MovieTickets",
  "mls-live>MSL Live",
  "mta-solutions>MTA Solutions",
  "mtv>MTV",
  "mu-legend>MU Legend",
  "mural>MURAL",
  "amazon-music-unlimited>Music Unlimited",
  "musically>Musical.ly",
  "myfitnesspal>My Fitness Pal",
  "my-social-security>My Social Security",
  "myq>MyQ",
  "namemc>NameMC",
  "naruto-storm>Naruto-Storm",
  "nba>National Basketball Association",
  "nationalgridus>National Grid NY",
  "nih>National Institutes of Health",
  "navy_federal_credit_union>Navy Federal Credit Union",
  "nba-2k>NBA 2k",
  "nbc-sports-live-extra>NBC Sports Live Extra",
  "nbc-news>NBCNews.com",
  "nctc>NCTC",
  "nearpod>Nearpod",
  "need-for-speed>Need for Speed",
  "nemr>NEMR",
  "nest>Nest",
  "net10>Net10 Wireless",
  "netatmo>Netatmo",
  "netblazr>netBlazr",
  "neteller>Neteller",
  "netflix>Netflix",
  "netfortris>NetFortris",
  "netsuite>Netsuite",
  "nettalk>Nettalk",
  "network-solutions>Network Solutions",
  "netzero>NetZero",
  "neverwinter>Neverwinter",
  "new-jersey-transit>New Jersey Transit",
  "new-york-mta>New York MTA",
  "new-york-state>New York State",
  "new-york-times>New York Times",
  "newegg>Newegg",
  "nextdoor>Nextdoor",
  "nextiva>Nextiva",
  "nfl-network>NFL Network",
  "nhl-tv>NHL.tv",
  "nicehash>Nicehash",
  "nifty>Nifty",
  "nikeplus>NikePlus",
  "nintendo-eshop>Nintendo eShop",
  "nintendo-network>Nintendo Network",
  "nintendo-switch-online>Nintendo Switch Online",
  "no-mans-sky>No Man&#x27;s Sky",
  "nomura>Nomura Holding, Inc",
  "nook>Nook",
  "nord-vpn>NordVPN",
  "nortex-communications>Nortex Communications",
  "north-state>North State",
  "northland>Northland Communications",
  "norwoodlight>Norwood Light",
  "notion>Notion",
  "npm>NPM",
  "us-ntt>NTT Communications",
  "nuget>NuGet",
  "nvidia>Nvidia",
  "oculus>Oculus",
  "offerup>OfferUp",
  "office-365>Office 365",
  "okcupid>OkCupid",
  "okta>Okta",
  "omegle>Omegle",
  "onedrive>OneDrive",
  "onelogin>Onelogin",
  "onstar>OnStar",
  "ooma>Ooma",
  "oovoo>ooVoo",
  "opendns>OpenDNS",
  "opera>Opera",
  "opticaltel>OpticalTel",
  "optimum-cablevision>Optimum / Cablevision",
  "oracle-cloud>Oracle Cloud",
  "orbitz>Orbitz",
  "origin>Origin",
  "outlook>Outlook",
  "outriders>Outriders",
  "overdrive>Overdrive",
  "overwatch>Overwatch",
  "ovh>OVH",
  "png>Pacific Northern Gas ",
  "pacific_power>Pacific Power",
  "page-plus>Page Plus",
  "pagely>Pagely",
  "paladins>Paladins",
  "pandora>Pandora",
  "panopto>Panopto",
  "paperspace>Paperspace",
  "epicgames-paragon>Paragon",
  "paramountplus>Paramount+",
  "patco>PATCO",
  "path>PATH",
  "path-of-exile>Path of Exile",
  "patreon>Patreon",
  "payday_2>PAYDAY 2",
  "paypal>Paypal",
  "pcloud>pCloud",
  "peacock>Peacock",
  "peloton>Peloton",
  "penteledata>PenTeleData",
  "periscope>Periscope",
  "personal-capital>Personal Capital",
  "pes>PES",
  "pge>PG&amp;E",
  "pga-tour-live>PGA Tour Live",
  "phasmophobia>Phasmophobia",
  "philo>Philo",
  "phonepower>Phonepower",
  "phonoscope-fiber>Phonoscope Fiber",
  "photobucket>Photobucket",
  "piggtbackr>Piggybackr",
  "pinterest>Pinterest",
  "plaid>Plaid",
  "planetzoo>Planet Zoo",
  "planetside2>Planetside2",
  "playbattlegrounds>Player Unknown&#x27;s Battlegrounds",
  "playstation-network>Playstation Network",
  "playstation-vue>Playstation Vue",
  "pof>PlentyOfFish",
  "plex>Plex",
  "pnc>PNC",
  "pokemon-duel>Pokémon Duel",
  "pokemon-go>Pokémon Go",
  "pokerstars>Pokerstars",
  "polar-communications>Polar Communications",
  "poloniex>Poloniex",
  "postmates>Postmates",
  "powerschool>Powerschool",
  "pozible>Pozible",
  "phs>Presbyterian Healthcare Services",
  "prey>Prey",
  "prezi>Prezi",
  "priceline>Priceline",
  "printify>Printify",
  "procore>Procore",
  "project>Project Online",
  "proofpoint>Proofpoint",
  "protonmail>ProtonMail",
  "pupilpath>PupilPath",
  "pypi>PyPi",
  "qlik>Qlik",
  "quad9>Quad9",
  "quake>Quake Champions",
  "questrade>Questrade",
  "quickbooks-intuit>Quickbooks Online",
  "quicken>Quicken",
  "quizlet>Quizlet",
  "quizup>Quizup",
  "quora>Quora",
  "rabbit>Rabb.it",
  "race-communications>Race Communications",
  "rackspace>Rackspace",
  "rainworldgame>Rain World Game",
  "rainbow-six>Rainbow Six",
  "razer>Razer",
  "rbc>RBC",
  "rcn>RCN",
  "realm-royale>Realm Royale",
  "recaptcha>reCAPTCHA",
  "red-dead-redemption>Red Dead Redemption",
  "redbox>Redbox",
  "reddit>Reddit",
  "redfin>Redfin",
  "reflexion>Reflexion",
  "renweb>Renweb",
  "residentevil2>RESIDENT EVIL 2",
  "restream>Restream",
  "returnal>Returnal",
  "revolut>Revolut",
  "ring>Ring",
  "ringbyname>RingByName",
  "ringcentral>RingCentral",
  "rise-broadband>Rise Broadband",
  "robinhood>Robinhood",
  "roblox>Roblox",
  "rocket-league>Rocket League",
  "rocket-rez>RocketRez",
  "roku>Roku",
  "roll20>Roll20",
  "royal-games>Royal Games",
  "rubygems>RubyGems",
  "runescape>Runescape",
  "runkeeper>Runkeeper",
  "runtastic>Runtastic",
  "rust>Rust",
  "ruzzle>Ruzzle",
  "ryver>Ryver",
  "safelink-wireless>Safelink Wireless",
  "safenet>Safenet",
  "sageone>SageOne",
  "salesforcecom>Salesforce",
  "samsung-shop>Samsung",
  "santander_bank>Santander Bank",
  "sarahah>Sarahah",
  "savvas-realize>Savvas Realize",
  "schooldesk>Schooldesk",
  "schoology>Schoology",
  "schoolpass>SchoolPass",
  "scottrade>Scottrade",
  "screenconnect>ScreenConnect",
  "scum>Scum",
  "sea-of-thieves>Sea of Thieves",
  "sec-network>SEC Network",
  "secom>Secom",
  "second-life>Second Life",
  "securely>Securely",
  "segra>Segra",
  "sense>Sense",
  "septa>SEPTA",
  "service-electric>Service Electric",
  "service-fusion>Service Fusion",
  "service-now>ServiceNow",
  "sharebuilder>Sharebuilder",
  "sharefile>Sharefile",
  "sharepoint>Sharepoint Online",
  "shentel>Shentel",
  "shopify>Shopify",
  "shoretel>Shoretel",
  "showtime-anytime>Showtime Anytime",
  "shutterstock>Shutterstock",
  "sifibe>Sifibe",
  "signal>Signal",
  "signupgenius>SignupGenius",
  "simple>Simple",
  "simple-mobile>Simple Mobile",
  "simplisafe>SimpliSafe",
  "siri>Siri",
  "siriusxm>SiriusXM",
  "skillshare>Skillshare",
  "skoda-connect>Skoda Connect",
  "skrill>Skrill",
  "skybest>SkyBest/SkyLine",
  "skype>Skype",
  "skype-for-business>Skype for Business",
  "skyscanner>Skyscanner",
  "skyswitch>SkySwitch",
  "skyward>Skyward",
  "skywest>SkyWest",
  "slack>Slack",
  "slashdot>Slashdot",
  "sleeper>Sleeper",
  "slideshare>Slideshare",
  "sling>Sling",
  "smart-hub>Smart Hub",
  "smartcom-telephone>Smartcom Telephone",
  "smartsheet>Smartsheet",
  "smartthings>SmartThings",
  "smite>Smite",
  "snap-ebt>SNAP EBT",
  "snapchat>Snapchat",
  "socket-telecom>Socket",
  "sonic-net>Sonic.net",
  "sonos>Sonos",
  "soundcloud>Soundcloud",
  "soundtrap>Soundtrap",
  "sourceforge>Sourceforge",
  "socen>South Central Communications",
  "sce>Southern California Edison",
  "southwest-airlines>Southwest Airlines",
  "sparklight>Sparklight",
  "spectrum>Spectrum",
  "speedtest>Speedtest",
  "splashid>SplashID",
  "splunk>Splunk",
  "spok>Spok Inc",
  "spotify>Spotify",
  "spyrothedragon>Spyro",
  "square>Square",
  "squarespace>Squarespace",
  "stackexchange>Stack Exchange",
  "stackoverflow>Stackoverflow",
  "stadia>Stadia",
  "staminus>Staminus",
  "stamps-com>Stamps.com",
  "star-citizen>Star Citizen",
  "star-wars-battlefront>Star Wars Battlefront",
  "starwars-jedi-fallen-order>Star Wars Jedi:  Fallen Order",
  "starbucks>Starbucks",
  "starlink>Starlink",
  "startrek-house-divided>Startrek Online: House Divided",
  "starz>Starz",
  "oregon>State of Oregon",
  "steam>Steam",
  "steep-ubisoft>Steep",
  "straight-talk>Straight Talk",
  "strava>Strava",
  "streamlabs>Streamlabs",
  "strife>Strife",
  "stripe>Stripe",
  "stylish>Stylish",
  "suddenlink-communications>Suddenlink",
  "suitebox>Suitebox",
  "summit-broadband>Summit Broadband",
  "summoners-war>Summoners War",
  "suntrust-bank>SunTrust Bank",
  "surfline>Surfline",
  "surveymonkey>SurveyMonkey",
  "synchrony-bank>Synchrony Bank",
  "t-mobile>T-Mobile",
  "t-rowe-price>T. Rowe Price",
  "taichi-panda>Taichi Panda",
  "talkray>Talkray",
  "tango>Tango",
  "target>Target",
  "tata-communications>Tata Communications",
  "taxslayer>Taxslayer",
  "td-ameritrade>TD Ameritrade",
  "tdbank>TD Bank",
  "tds-telecom>TDS Telecom",
  "teamviewer>Teamviewer",
  "tekken>Tekken",
  "telecharge>Telecharge",
  "telegram>Telegram",
  "tennis-tv>Tennis TV",
  "tera>TERA",
  "tesla>Tesla",
  "the-crew>The Crew 2",
  "the-culling>The Culling",
  "the-division>The Division",
  "the-elder-scrolls-online>The Elder Scrolls Online",
  "home-depot>The Home Depot",
  "huffington-post>The Huffington Post",
  "the-last-of-us>The Last Of Us",
  "outerworlds>The Outer Worlds",
  "the-simpsons>The Simpsons Tapped out",
  "the-sims-4>The Sims 4",
  "the-weather-channel>The Weather Channel",
  "thingiverse>Thingiverse",
  "thinkific>Thinkific",
  "threads>Threads",
  "threema>Threema",
  "tiaa>TIAA",
  "ticketmaster>Ticketmaster",
  "tidal>Tidal",
  "tiktok>TikTok",
  "tinder>Tinder",
  "titanfall>Titanfall",
  "tivo>Tivo",
  "todoist>Todoist",
  "toggle>Toggl",
  "tpx-communications>TPx Communications",
  "tracfone-wireless>TracFone Wireless",
  "tradeking>Tradeking",
  "trade-satoshi>TradeSatoshi",
  "tradestation>TradeStation",
  "trakt>Trakt",
  "transferwise>Transferwise",
  "travelocity>Travelocity",
  "trello>Trello",
  "trove>Trove",
  "trusted-id>Trusted Id",
  "tsys>TSYS",
  "ttec>TTEC",
  "tumblr>Tumblr",
  "tunein>TuneIn",
  "tunnelbear>TunnelBear",
  "turbotax>TurboTax",
  "tutanota>Tutanota",
  "tv-time>TV Time",
  "tweakbox>Tweakbox",
  "tweetdeck>Tweetdeck",
  "twilio>Twilio",
  "twitch>Twitch",
  "twitter>Twitter",
  "txuenergy>TXU Energy",
  "uber>Uber",
  "uber-eats>Uber Eats",
  "udacity>Udacity",
  "udemy>Udemy",
  "ufc>UFC",
  "ulule>Ulule",
  "umg-gaming>UMG Gaming",
  "uncharted>Uncharted",
  "united-airlines>United Airlines",
  "unrollme>Unroll.Me",
  "untappd>Untappd",
  "untitledgoosegame>Untitled Goose Game",
  "updraftplus>UpdraftPlus",
  "uplay>Uplay PC",
  "ups>UPS",
  "upwork>Upwork",
  "us-bank>US Bank",
  "us-cellular>US Cellular",
  "usaa>USAA",
  "usps>USPS",
  "utahbroadband>Utah Broadband",
  "vainglory>Vainglory",
  "valorant>Valorant",
  "vanguard>Vanguard",
  "varo>Varo",
  "vastbroadband>Vast Broadband",
  "vectren>Vectren",
  "venmo>Venmo",
  "verizon>Verizon",
  "vero>Vero",
  "viaero>Viaero",
  "viasat>Viasat",
  "viber>Viber",
  "vidangel>VidAngel",
  "viewster>Viewster",
  "viki>Viki",
  "vimeo>Vimeo",
  "vine>Vine",
  "vipkid>VIPKid",
  "virgin-mobile>Virgin Mobile",
  "visa>Visa",
  "visible>Visible",
  "visionary-broadband>Visionary Broadband",
  "visual-studio>Visual Studio Team Services",
  "v-live>Vlive",
  "vonage>Vonage",
  "voxer>Voxer",
  "vpn-unlimited>VPN Unlimited",
  "vrchat>VRChat",
  "vrv>VRV",
  "vudu>Vudu",
  "broadbandnow>Vyve Broadband",
  "w3schools>W3Schools",
  "waiter-com>Waiter.com",
  "walmart-family-mobile>Walmart Family",
  "wal-mart>Walmart.com",
  "war-thunder>War Thunder",
  "warface>Warface",
  "warframe>Warframe",
  "washington-metropolitan-area-transit-authority>Washington Metropolitan Area Transit Authority",
  "wattpad>Wattpad",
  "wave-broadband>Wave Broadband",
  "wayfair>Wayfair",
  "waze>Waze",
  "webassign>Webassign",
  "webex>Webex",
  "webhosting-net>Webhosting.net",
  "webreus>Webreus",
  "webs>Webs",
  "webtoon>Webtoon",
  "webull>Webull",
  "weebly>Weebly",
  "wefunder>Wefunder",
  "weightwatchers>Weight Watchers",
  "wells-fargo>Wells Fargo",
  "wemo>Wemo",
  "westman>Westman",
  "wetransfer>WeTransfer",
  "whatsapp>Whatsapp",
  "whatsapp-business>WhatsApp Business",
  "whisper>Whisper",
  "wikipedia>Wikipedia",
  "wilcoinc>Wilco Inc",
  "wildstar>Wildstar",
  "wiline>WiLine",
  "william-hill>William Hill",
  "wimkin>Wimkin",
  "windermere>Windermere Real Estate",
  "windstream>Windstream",
  "wish>Wish",
  "wix>Wix",
  "wolters-kluwer>Wolters Kluwer",
  "wordpresscom>Wordpress.com",
  "workday>Workday",
  "who>World Health Organization",
  "world-of-tanks>World of Tanks",
  "world-of-warcraft>World of Warcraft",
  "world-of-warships>World of Warships",
  "world-war-3>World War 3",
  "world-war-z>World War Z",
  "wow>WOW",
  "wow-presents-plus>WOW Presents Plus",
  "wp-engine>WP Engine",
  "wunderground>Wunderground",
  "wunderlist>Wunderlist",
  "wwenetwork>WWE Network",
  "wyze>Wyze",
  "xbox-live>Xbox Live",
  "xfinity>Xfinity",
  "xfinity-flex>Xfinity Flex",
  "xoom>Xoom",
  "yahoo>Yahoo",
  "yahoo-mail>Yahoo Mail",
  "yahoo-messenger>Yahoo Messenger",
  "yammer>Yammer",
  "yelp>Yelp",
  "yodlee>Yodlee",
  "youtube>Youtube",
  "youtube-music>Youtube Music",
  "youtube-tv>Youtube TV",
  "yubo>Yubo",
  "h1z1>Z1 Battle Royale",
  "zayo>Zayo",
  "zelle>Zelle",
  "zendesk>Zendesk",
  "zettle>Zettle",
  "zillow>Zillow",
  "ziply_fiber>Ziply Fiber",
  "zoho>ZoHo",
  "zoom>Zoom",
  "zultys>Zultys Inc",
  "zwift>Zwift",
  "zynga>Zynga"]

  useEffect(() => {
    const services = values.map(service => {
      const splited = service.split('>')

      const value = splited[0]
      const option = splited[1]

      return {
        value,
        option
      }
    })

    setOptions(services)
  }, [])

  return options
}