import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import moment from 'moment'

import {
  AreaChart,
  ResponsiveContainer,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Area
} from 'recharts'

import { Graph } from './../components'

import { useServices } from './../hooks'

import styles from '../styles/Home.module.css'

interface reportDataInterface {
  x: string;
  y: number;
}

const Home: NextPage = () => {
  const services = useServices()
  moment.locale('pt-br')

  function normalizeData(baselineData: Array<reportDataInterface>, reportsData: Array<reportDataInterface>) {
    const data = baselineData.map((baseline, index) => {
      const x = baseline.y
      const y = reportsData[index].y

      return {
        hour: moment(baseline['x']).format('HH:mm:ss'),
        uv: x,
        pv: y
      }
    })

    return data
  }

  function renderServices() {
    return services.map((service, index) => {
      const content = service.content
      const data = normalizeData(content.baseline, content.reports)

      return (
        <Graph
          key={String(index)}
          name={service.name}
          data={data}
        />
      )
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {renderServices()}
      </main>

      {/* <defs></defs> */}

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
